name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  build_skim:
    needs: greeting
    runs-on: ubuntu-latest
    container: rootproject/root:${{ matrix.version }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      matrix:
        version: [6.26.10-conda]
        allow_failure: [false]
        include:
          - version: [latest]
            allow_failure: [true]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build
        run: |
          FLAGS=$(root-config --cflags --libs)
          COMPILER=$(root-config --cxx)
          $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS
